- name: Deploy Chat App to EC2
  hosts: chat_servers
  become: yes
  vars:
    docker_image_backend: "{{ docker_image_backend }}"
    docker_image_frontend: "{{ docker_image_frontend }}"
    mongo_data_dir: "/data/db"
  tasks:
    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64"
        dest: "/usr/local/bin/docker-compose"
        mode: "0755"

    - name: Copy Docker Compose file
      copy:
        src: ../docker-compose.yml
        dest: /home/ec2-user/docker-compose.yml

    - name: Deploy application
      shell: |
        docker-compose -f /home/ec2-user/docker-compose.yml up -d
